# **Feature Engineering**
FE is the process of creating, transforming ad selecting the most revelvant variables (features) from raw data to improve model perfromance.

**Features**: Relevant variables 

-----

In [2]:
import pandas as pd
import numpy as np

In [3]:
housing_csv = pd.read_csv('Housing.csv')

In [4]:
housing_csv.head(15)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished


In [5]:
housing_new = housing_csv.select_dtypes(include = np.number)
print(housing_new.head(15))
print(housing_new.shape)
print(housing_new.tail(15))

       price   area  bedrooms  bathrooms  stories  parking
0   13300000   7420         4          2        3        2
1   12250000   8960         4          4        4        3
2   12250000   9960         3          2        2        2
3   12215000   7500         4          2        2        3
4   11410000   7420         4          1        2        2
5   10850000   7500         3          3        1        2
6   10150000   8580         4          3        4        2
7   10150000  16200         5          3        2        0
8    9870000   8100         4          1        2        2
9    9800000   5750         3          2        4        1
10   9800000  13200         3          1        2        2
11   9681000   6000         4          3        2        2
12   9310000   6550         4          2        2        1
13   9240000   3500         4          2        2        2
14   9240000   7800         3          2        2        0
(545, 6)
       price  area  bedrooms  bathrooms  storie

## **Absolute Maximum Scaling**



In [6]:
max_abs = np.max(np.abs(housing_new), axis = 0)
print(max_abs)
scaled_df = housing_new / max_abs
print(scaled_df.head(15))
print(scaled_df.tail(15))

price        13300000
area            16200
bedrooms            6
bathrooms           4
stories             4
parking             3
dtype: int64
       price      area  bedrooms  bathrooms  stories   parking
0   1.000000  0.458025  0.666667       0.50     0.75  0.666667
1   0.921053  0.553086  0.666667       1.00     1.00  1.000000
2   0.921053  0.614815  0.500000       0.50     0.50  0.666667
3   0.918421  0.462963  0.666667       0.50     0.50  1.000000
4   0.857895  0.458025  0.666667       0.25     0.50  0.666667
5   0.815789  0.462963  0.500000       0.75     0.25  0.666667
6   0.763158  0.529630  0.666667       0.75     1.00  0.666667
7   0.763158  1.000000  0.833333       0.75     0.50  0.000000
8   0.742105  0.500000  0.666667       0.25     0.50  0.666667
9   0.736842  0.354938  0.500000       0.50     1.00  0.333333
10  0.736842  0.814815  0.500000       0.25     0.50  0.666667
11  0.727895  0.370370  0.666667       0.75     0.50  0.666667
12  0.700000  0.404321  0.666667    

## **Min Max scaling**

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled_data = scaler.fit_transform(housing_new)
print(scaled_data)

scaled_df = pd.DataFrame(scaled_data, columns = housing_new.columns)

print(scaled_df.head(15))

print(scaled_df.tail(15))

[[1.         0.39656357 0.6        0.33333333 0.66666667 0.66666667]
 [0.90909091 0.5024055  0.6        1.         1.         1.        ]
 [0.90909091 0.57113402 0.4        0.33333333 0.33333333 0.66666667]
 ...
 [0.         0.13539519 0.2        0.         0.         0.        ]
 [0.         0.08659794 0.4        0.         0.         0.        ]
 [0.         0.15120275 0.4        0.         0.33333333 0.        ]]
       price      area  bedrooms  bathrooms   stories   parking
0   1.000000  0.396564       0.6   0.333333  0.666667  0.666667
1   0.909091  0.502405       0.6   1.000000  1.000000  1.000000
2   0.909091  0.571134       0.4   0.333333  0.333333  0.666667
3   0.906061  0.402062       0.6   0.333333  0.333333  1.000000
4   0.836364  0.396564       0.6   0.000000  0.333333  0.666667
5   0.787879  0.402062       0.4   0.666667  0.000000  0.666667
6   0.727273  0.476289       0.6   0.666667  1.000000  0.666667
7   0.727273  1.000000       0.8   0.666667  0.333333  0.000000
8   

## **Eucledian Method**

In [8]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()

scaled_data = scaler.fit_transform(housing_new)

scaled_df = pd.DataFrame(scaled_data, columns = housing_new.columns)

print(scaled_df.head(15))
print(scaled_df.tail(15))

       price      area      bedrooms     bathrooms       stories       parking
0   1.000000  0.000558  3.007518e-07  1.503759e-07  2.255639e-07  1.503759e-07
1   1.000000  0.000731  3.265305e-07  3.265305e-07  3.265305e-07  2.448979e-07
2   1.000000  0.000813  2.448979e-07  1.632653e-07  1.632653e-07  1.632653e-07
3   1.000000  0.000614  3.274662e-07  1.637331e-07  1.637331e-07  2.455996e-07
4   1.000000  0.000650  3.505696e-07  8.764240e-08  1.752848e-07  1.752848e-07
5   1.000000  0.000691  2.764976e-07  2.764976e-07  9.216588e-08  1.843318e-07
6   1.000000  0.000845  3.940885e-07  2.955664e-07  3.940885e-07  1.970443e-07
7   0.999999  0.001596  4.926102e-07  2.955661e-07  1.970441e-07  0.000000e+00
8   1.000000  0.000821  4.052684e-07  1.013171e-07  2.026342e-07  2.026342e-07
9   1.000000  0.000587  3.061224e-07  2.040816e-07  4.081632e-07  1.020408e-07
10  0.999999  0.001347  3.061222e-07  1.020407e-07  2.040814e-07  2.040814e-07
11  1.000000  0.000620  4.131804e-07  3.098853e-07  

## **Standardization**

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_data = scaler.fit_transform(housing_new)
print(scaled_data)
scaled_df = pd.DataFrame(scaled_data, columns = housing_new.columns)

print(scaled_df.head(15))
print(scaled_df.tail(15))

[[ 4.56636513  1.04672629  1.40341936  1.42181174  1.37821692  1.51769249]
 [ 4.00448405  1.75700953  1.40341936  5.40580863  2.53202371  2.67940935]
 [ 4.00448405  2.21823241  0.04727831  1.42181174  0.22441013  1.51769249]
 ...
 [-1.61432675 -0.70592066 -1.30886273 -0.57018671 -0.92939666 -0.80574124]
 [-1.61432675 -1.03338891  0.04727831 -0.57018671 -0.92939666 -0.80574124]
 [-1.61432675 -0.5998394   0.04727831 -0.57018671  0.22441013 -0.80574124]]
       price      area  bedrooms  bathrooms   stories   parking
0   4.566365  1.046726  1.403419   1.421812  1.378217  1.517692
1   4.004484  1.757010  1.403419   5.405809  2.532024  2.679409
2   4.004484  2.218232  0.047278   1.421812  0.224410  1.517692
3   3.985755  1.083624  1.403419   1.421812  0.224410  2.679409
4   3.554979  1.046726  1.403419  -0.570187  0.224410  1.517692
5   3.255309  1.083624  0.047278   3.413810 -0.929397  1.517692
6   2.880722  1.581745  1.403419   3.413810  2.532024  1.517692
7   2.880722  5.096263  2.759560

## **Robust Scaling**

Robust scaling uses median and Interquartile range instead of mean and and standard deviation making trasformation less sensitive to outliers, making transformation more robust with skewed distribution.

**IQR = Q3 - Q1**

In [10]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

scaled_data = scaler.fit_transform(housing_new)

scaled_df = pd.DataFrame(scaled_data, columns = housing_new.columns)

print(scaled_df.head(15))
print(scaled_df.tail(15))

       price      area  bedrooms  bathrooms  stories  parking
0   3.878788  1.021739       1.0        1.0      1.0      2.0
1   3.424242  1.579710       1.0        3.0      2.0      3.0
2   3.424242  1.942029       0.0        1.0      0.0      2.0
3   3.409091  1.050725       1.0        1.0      0.0      3.0
4   3.060606  1.021739       1.0        0.0      0.0      2.0
5   2.818182  1.050725       0.0        2.0     -1.0      2.0
6   2.515152  1.442029       1.0        2.0      2.0      2.0
7   2.515152  4.202899       2.0        2.0      0.0      0.0
8   2.393939  1.268116       1.0        0.0      0.0      2.0
9   2.363636  0.416667       0.0        1.0      2.0      1.0
10  2.363636  3.115942       0.0        0.0      0.0      2.0
11  2.312121  0.507246       1.0        2.0      0.0      2.0
12  2.151515  0.706522       1.0        1.0      0.0      1.0
13  2.121212 -0.398551       1.0        1.0      0.0      2.0
14  2.121212  1.159420       0.0        1.0      0.0      0.0
        

In [11]:
housing_csv.shape

(545, 13)

In [12]:
housing_csv.tail(15)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
530,2240000,1950,3,1,1,no,no,no,yes,no,0,no,unfurnished
531,2233000,5300,3,1,1,no,no,no,no,yes,0,yes,unfurnished
532,2135000,3000,2,1,1,no,no,no,no,no,0,no,unfurnished
533,2100000,2400,3,1,2,yes,no,no,no,no,0,no,unfurnished
534,2100000,3000,4,1,2,yes,no,no,no,no,0,no,unfurnished
535,2100000,3360,2,1,1,yes,no,no,no,no,1,no,unfurnished
536,1960000,3420,5,1,2,no,no,no,no,no,0,no,unfurnished
537,1890000,1700,3,1,2,yes,no,no,no,no,0,no,unfurnished
538,1890000,3649,2,1,1,yes,no,no,no,no,0,no,unfurnished
539,1855000,2990,2,1,1,no,no,no,no,no,1,no,unfurnished
